###############################################################################
# Find components
###############################################################################
function(find_p4c_bm2_ss REQUIRED)
  find_program(P4C_BM2_SS p4c-bm2-ss ${ARGN})
  if(P4C_BM2_SS)
    message("-- Check for p4c-bm2-ss: ${P4C_BM2_SS}")
  else()
    message("-- Check for p4c-bm2-ss: not found")
    if(REQUIRED)
      message(FATAL_ERROR "p4c-bm2-ss is required")
    endif()
  endif()
endfunction()

function(find_p4c_bm2_psa REQUIRED)
  find_program(P4C_BM2_PSA p4c-bm2-psa ${ARGN})
  if(P4C_BM2_PSA)
    message("-- Check for p4c-bm2-psa: ${P4C_BM2_PSA}")
  else()
    message("-- Check for p4c-bm2-psa: not found")
    if(REQUIRED)
      message(FATAL_ERROR "p4c-bm2-psa is required")
    endif()
  endif()
endfunction()

function(find_p4c_bm2_pna REQUIRED)
  find_program(P4C_BM2_PNA p4c-bm2-pna ${ARGN})
  if(P4C_BM2_PNA)
    message("-- Check for p4c-bm2-pna: ${P4C_BM2_PNA}")
  else()
    message("-- Check for p4c-bm2-pna: not found")
    if(REQUIRED)
      message(FATAL_ERROR "p4c-bm2-pna is required")
    endif()
  endif()
endfunction()
